'use client'
import React, { useState } from 'react'
import { notoBold, notoLight } from '@/app/fonts';
import { useRouter } from 'next/navigation'

const TermsOfUse = () => {
    const [termsAgreed, setTermsAgreed] = useState("");
    const formId = "termsConsentForm";
    const pageId = "Terms of Use Page";
    const router = useRouter()

    const handleCheckboxChange = (e: any) => {
        setTermsAgreed(e.target.checked);
    };

    const handleSubmit = (e: any) => {
        e.preventDefault();
        console.log('termsAgreed: ', termsAgreed);
        router.push("/pp/terms-of-use");
    }

    return (
        <div className={`${notoLight.className} mx-4 md:mx-40 my-16 text-sm`}>
            <p className='mb-4'>Welcome to Elevate Now mobile application or website (the &quot;Application&quot;). The Application is operated by Enlight Now Healthcare Private Limited, having its registered office at Cowrks, WorldMark 1, Tower A, Aerocity,  Indira Gandhi International Airport, Delhi - 110037.</p>
            <p className='mb-4'>The terms ‘You’ or ‘Your’ refer to you as the user (irrespective of whether You are a Registered User or a Non-Registered User) and the terms ‘Elevate Now’, ‘We’, ‘Us’, ‘Company’, and ‘Our’ refer to Elevate Now.  In the event the Application is being used by a person on your behalf, the expression “You” or “Your” shall apply to such third party as well.</p>
            <p className={`${notoBold.className} mb-4`}>
                PLEASE CAREFULLY READ THE FOLLOWING TERMS OF USE OF THE APPLICATION. THESE TERMS OF USE (AS AMENDED FROM TIME TO TIME), TOGETHER WITH THE ELEVATE NOW <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">PRIVACY POLICY</a> (AS AMENDED FROM TIME TO TIME) AVAILABLE AT <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">PRIVACY POLICY</a>, ANY ADDITIONAL SERVICE SPECIFIC TERMS AND CONDITIONS AND OTHER POLICIES WHICH MAY BE APPLICABLE TO SPECIFIC PORTIONS OF THIS APPLICATION CONSTITUTE THE TERMS OF YOUR ACCESS TO AND USAGE OF THE APPLICATION. BY CLICKING ON THE {"'"}I ACCEPT{"'"} BUTTON AT THE END OF THIS PAGE OR ACCESSING OR USING THIS APPLICATION, YOU AGREE TO BE BOUND BY THESE TERMS OF USE, THE <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">PRIVACY POLICY</a> AND OTHER POLICIES WHICH MAY BE APPLICABLE TO THIS APPLICATION. IF YOU DO NOT AGREE TO BE BOUND BY THEM PLEASE DO NOT ACCESS OR USE THE APPLICATION.
            </p>
            <p className='mb-4'>If You are accessing the Elevate Now mobile application, then there may be additional terms (such as the terms imposed by application stores) which may also govern the use of the mobile application. By clicking on the ‘I Accept’ button at the end of this page or accessing or using the mobile application, You agree to be bound by the aforesaid additional terms as may be amended from time to time.</p>
            <p className='mb-4'>These Terms of Use, the <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a>, together with any additional Service-specific terms and conditions, other policies which may be applicable to specific portions of the Application and any disclaimers which may be present on the Application are referred to as “Agreement”. Where any part of the Agreement is modified in accordance with the terms of the Agreement, the Agreement shall be enforceable in its modified form.</p>
            <p className='mb-4'>The features / services of the Application are available to Registered Users only in India. However, Non-Registered Users within India may browse through the information provided in the Application.</p>
            <p className='mb-4'>The Agreement supersedes all previous oral and written terms and conditions (if any) communicated to You.</p>

            <h3 className={`${notoBold.className} mb-4`}>THE APPLICATION</h3>
            <p className='mb-4'>Elevate Now is the author and publisher of the Application, and all variants, editions, add-ons, and ancillary products or services of the Application (including all files and images contained in or generated by the software, and accompanying data, together). The Application may be used by Users (defined below) to avail Services (defined below) and/or to find, access, manage and organize information including but not limited to personal or non-personal information, doctor/health coach/consultant information, appointments, prescriptions, laboratory and diagnostic tests, electronic medical records, billing, inventory, accounting details and other relevant information.</p>

            <h3 className={`${notoBold.className} mb-4`}>USERS</h3>
            <ul className='mb-4'>
                <li className='mb-4'>“Registered Users” are users who have successfully made applicable payments, registered and onboarded themselves with Elevate Now for availing Elevate Now’s Services by providing information that is true and accurate, and who can log on to their account on the Application by providing their username and password.</li>
                <li className='mb-4'>“Health Care Service Providers” or “HSPs” are duly qualified doctors,nurses, dieticians, health coaches, paramedical staff, physiotherapists,consultants, medical equipment suppliers, laboratory service providers, otherincidental and ancillary health care service providers who interact withRegistered Users as part of the Services.</li>
                <li className='mb-4'>“Non-Registered Users” are users who have not successfully registered themselves on the Application. Non-Registered Users may not be provided access to certain areas of the Application.</li>
                <li className='mb-4'>RegisteredUsers and Non-Registered Users shall individually or collectively be referredto as <span className={`${notoBold.className}`}>“Users”.</span></li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>ACCESS AND USAGE RIGHTS OF USERS</h3>
            <p className='mb-4'><span className={`${notoBold.className}`}>Non - Registered User:</span> A Non-Registered User is not permitted to access or make use of the Applicationfor any purpose other than what is specifically permitted.</p>
            <p className='mb-4'>A Non-Registered Useris specifically permitted to (subject to acceptance of the <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a>):</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>To browse the Elevate Now website without accessing any Services;</li>
                <li className='mb-4'>To share the Elevate Now website via social media applications;</li>
                <li className='mb-4'>Access certain questionnaires and provide details required to assess the eligibility for availing any Services.</li>
            </ol>
            <p className='mb-4'><span className={`${notoBold.className}`}>Registered User:</span> A Registered User is not permitted to access or make use of the Application for any purpose other than what is specifically permitted. </p>
            <p className='mb-4'>Registered User is specifically permitted to:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Enjoy all the access and usage rights of an Unregistered User;</li>
                <li className='mb-4'>Access and use the Services specifically subscribed to and subject to such limitations and restrictions as are prescribed under the Agreement or may be otherwise communicated to Registered User from time to time through any contact information shared by such user at the time of registration.</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>CONTENT</h3>
            <p className='mb-4'>The data and information available on the Application may be categorised as follows:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Data and information generated or provided by Unregistered Users and Registered Users on the Application (“User Content”)</li>
                <li className='mb-4'>Data and information which Elevate Now (through itself or its contractors) has generated or procured for the Application and includes data and information generated or provided by HSP (“Elevate Now Content”);</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>GENERAL TERMS OF USE</h3>
            <ul>
                <li className='mb-4'>You will use the Application and the features provided by the Application only in relation to and in compliance with all applicable Indian laws.</li>
                <li className='mb-4'>You will not use this Application or any feature provided by the Application for any purposes not intended under this Agreement.</li>
                <li className='mb-4'>You should not use this Application from outside of India. In a situation where You avail of any Service outside India which involves an Elevate Now doctor or HSP,</li>
                <li className='mb-4'>You should have any prescription issued or advice received validated by a local registered medical practitioner or relevant qualified service provider.</li>
                <li className='mb-4'>Certain Services are location specific. Depending on Your location, some Services may not be available to You.</li>
                <li className='mb-4'>You will not deliberately use the Application in any way that is unlawful or harms Elevate Now, its directors, employees, affiliates, distributors, partners, service providers and/or any User and/or data or content on the Application.</li>
                <li className='mb-4'>As a Registered or Non-Registered User, You may have access to business sensitive information. You shall not share such information with Elevate Now’s direct competitors, except with Elevate Now’s prior written consent.</li>
                <li className='mb-4'>You understand that as part of Your registration process as well as in course of Your use of the Application, You may receive SMS, telephone and/or email communication from Elevate Now on Your registered contact information. These communications will relate to Your registration, Services provided by Elevate Now, transactions that You carry out through the Application and any such information found suitable of Your attention by Elevate Now. Please note that Elevate Now will send these communications only to the mobile number that You provide on the Application. It is Your responsibility to ensure that You provide the correct number for the transaction You wish to enter into. Further, Elevate Now may also send notifications and reminders to You for the features that You may be using on the Application. You hereby consent to receive such communications from Elevate Now.</li>
                <li className='mb-4'>You will not share Your log-in details with anyone. You are responsible for maintaining the confidentiality of Your account access information and password. You shall be responsible for all usage of Your account and password, whether or not authorized by You. You shall immediately notify Elevate Now of any actual or suspected unauthorized use of the Your account or password. Although Elevate Now will not be liable for Your losses caused by any unauthorized use of Your account, You may be liable for the losses of Elevate Now or others due to such unauthorized use.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>SERVICES</h3>
            <p className='mb-4'>The Application may be used to access a variety of health care and related services. Depending on the status of Your registration and subject to the limitations and restrictions imposed by the Agreement or by Elevate Now, You may avail of the following services through the Application (provided by Elevate Now or through third party independent contractors):</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Online Coaching/Consultations;</li>
                <li className='mb-4'>Lab/sample collections;</li>
                <li className='mb-4'>Built-in app features such as reminders, storage and display of Your medical records, information and history, including general medical information, outpatient records, discharge summaries, prescriptions, lab investigations and radiology reports;</li>
                <li className='mb-4'>Prescription of certain medication as deemed fit by doctor physicians</li>
                <li className='mb-4'>Any physical devices or instruments as part of care kit, deemed fit by Elevate Now for successful delivery of its Services</li>
                <li className='mb-4'>Delivery of medicines from third party suppliers in case if they are ordered by Elevate Now on behalf of patient</li>
                <li className='mb-4'>Such other services as may be intimated from time to time.</li>
            </ol>
            <ul>
                <li className='mb-4'>The Services are non-transferable and only cover the Registered User.</li>
                <li className='mb-4'>The initiation, duration, pricing and terms of any specific Service availed by You, along with any additional terms and conditions not specifically covered under this Agreement shall be separately communicated to You as and when you decide to avail of such Service. Where the price for a Service is displayed on the Application or separately communicated to You, You agree to such pricing where You avail of the Service. Certain discounts may be made available to You from time to time, at the sole discretion of Elevate Now. Elevate Now expressly reserves the right to change/modify/withdraw such discounts based on various factors including ongoing campaigns, geographies, channels, etc.</li>
                <li className='mb-4'>Registered Users who decide to avail Services in connection with health coaching which includes diet programs, fitness coaching, educational modules online consultations and screening test (“Health Consultation Services”) must be at least 18 years of age and sound mind.</li>
                <li className='mb-4'>You are advised not to use the Services in the following situations:</li>
                <li className='mb-4'>You are below 18 years of age or above 65 years of age</li>
                <li className='mb-4'>Any disqualifying factor as identified in the eligibility form provided to You.</li>
                <li className='mb-4'>If You are a Registered User but do not satisfy the above pre-conditions, please do not avail the Health Consultation Services. Elevate Now will not be responsible or liable for any harm or loss that You may suffer if You elect to access those Services.</li>
                <li className='mb-4'>All Users, who are patients, and who opt for Health Consultation Services, may be required to undergo an initial medical examination to ascertain and record medical history, medication history and medical status before video-consulting support can be provided.</li>
                <li className='mb-4'>Health Consultation Services may be provided via the following communication channels [Call Center Helplines / Telephones / Mobiles / IM Chats / Online Chats / SMS & Text Chats with and without camera and video facilities]. Reasonable efforts will be made to protect Your privacy and confidentiality across Health Consultation Services.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>ELEVATE NOW’S RIGHTS TO THE APPLICATION AND ELEVATE NOW CONTENT</h3>
            <p className='mb-4'>Elevate Now respects the intellectual property rights of others, and We expect the same from You. The Application, User Content and the Elevate Now Content are protected by applicable intellectual property laws.</p>

            <h2 className='mb-4'>Elevate Now’s Rights to the Application and Elevate Now Content:</h2>
            <ul>
                <li className='mb-4'>All intellectual property in and to the Application and all software, techniques and processes used in connection with the aforesaid, belongs exclusively to Elevate Now or its licensors. As a User, You are granted a limited license to access and use the Application as per the terms of the Agreement. Through Your use of the Application, by no means are any intellectual property rights impliedly or expressly granted by Elevate Now to You in respect of such works.</li>
                <li className='mb-4'>Elevate Now and/or its licensors assert all proprietary rights in and to all names and trademarks contained on the Application. Notwithstanding the generality of the foregoing, the name and logos of “Elevate Now” [is/are] the trademarks and copyright (inclusive of any other applicable intellectual property right) of Elevate Now and/or its licensors. Any use of the such name or logo, unless otherwise authorized in a written agreement, will constitute an infringement upon the trademark and copyright (or any other such intellectual property right) of Elevate Now and/or its licensors and may be actionable under applicable laws.</li>
                <li className='mb-4'>Except as stated otherwise in this Agreement, all Elevate Now Content (including all intellectual property rights to such content) is owned exclusively by Elevate Now and/or its licensors.</li>
                <li className='mb-4'>When You use the Application in accordance with this Agreement, a limited royalty-free right is granted to You by Elevate Now to use Elevate Now Content for personal and non-commercial use in India for the term of the Agreement.</li>
                <li className='mb-4'>Unless explicitly stated herein, nothing in this Agreement shall be construed as conferring on You any license to intellectual property rights, whether by estoppel, implication, or otherwise.</li>
                <li className='mb-4'>Unless expressly authorized by Elevate Now, You agree not to reproduce, modify, sell, distribute, mirror, frame, republish, download, transmit, or create derivative works of the Elevate Now Content, in whole or in part, by any means. You must not remove or modify any copyright or trademark notice, or other notice of ownership.</li>
            </ul>

            <h2 className='mb-4'>Rights in User Content:</h2>
            <ul>
                <li className='mb-4'>You agree that You are the owner of all rights (including all intellectual property rights) in the User Content that You post on the Application or provide to Elevate Now.</li>
                <li className='mb-4'>To the extent permissible by law, You hereby grant Elevate Now a perpetual, non-revocable, worldwide, royalty-free license to make use of such User Content including the right to copy, distribute, display, reproduce, modify, adapt, the User Content, and create derivate works of the User Content.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>PATIENT CONSENT & PRIVACY</h3>
            <ul>
                <li className='mb-4'>You have the option of uploading Your personally identifiable health information including physical, physiological and mental health condition, and medical records and history on the Application which may be accessed by Elevate Now and/or HSPs using the Application, during the course of providing Services to You.</li>
                <li className='mb-4'>We may collect various personal information from You when You use the Application and for the features provided by the Application.</li>
                <li className='mb-4'>Our Privacy Policy available at <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">PRIVACY POLICY</a> sets out Our policy with respect to the collection, storage, use, transfer and protection of any such personal information.</li>
                <li className='mb-4'>When You click on the ‘I accept’ tab at the time of registering or access the Application or otherwise provide Your personal information, You specifically consent to Our <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a>.</li>
                <li className='mb-4'>Elevate Now may disclose/transfer Your Personal Information in accordance with applicable law and for the purposes as set out in the Elevate Now <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a></li>
                <li className='mb-4'>Elevate Now is required by law to maintain the privacy of Your medical information. We assure to take Your privacy seriously and to maintain privacy and confidentiality of the information provided by You to us. We however do not represent, warrant or guarantee that our safeguards to prevent unauthorized access to Your personal information is fool-proof.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>OTHER WEBSITES/MOBILE APPLICATIONS</h3>
            <ul>
                <li className='mb-4'>You may be provided with links on the Application that direct You to third party websites / applications / content or service providers (collectively “Third Party Content”).</li>
                <li className='mb-4'>Links to such Third Party Applications are provided for Your convenience only. Please exercise Your independent judgment and prudence when visiting / using any Third Party Content via a link available on the Application.</li>
                <li className='mb-4'>Should You decide to click on the links to visit such Third Party Content, You do so on Your own volition. Your usage of such Third Party Content is subject to the terms of use of the respective Third Party Content and Elevate Now is not responsible for Your use of any Third Party Content.</li>
                <li className='mb-4'>We do not extend the Agreement to any other websites/applications except for this Application. We do not make any warranty or give any security to the personal information disclosed by You to the other websites/applications, even if such websites/applications are linked to our Application or they are using our Application link.</li>
                <li className='mb-4'>Elevate Now does not endorse any Third Party Content that You may be directed to from the Application.</li>
                <li className='mb-4'>ELEVATE NOW RESPONSIBILITIES</li>
            </ul>

            <h2 className={`${notoBold.className} mb-4 text-xl`}>HSPs</h2>
            <ul>
                <li className='mb-4'>Elevate Now will make available qualified HSPs to render Services after carrying out appropriate background and reference checks.</li>
                <li className='mb-4'>It is hereby clarified Elevate Now’s obligation to carry out appropriate background and reference checks and to validate qualification of HSPs does not go beyond ensuring that the HSPs were registered with relevant state professional councils or central professional council (where applicable to the HSP) at the time of engagement and had a certificate of good standing from the relevant professional council at the time of engagement.</li>
                <li className='mb-4'>The HSP is solely responsible for the Services provided to You and will use his/her professional skill and judgement in providing such Services, which shall include formulating a treatment/health plan, lifestyle and diet recommendations as deemed appropriate by the HSP.</li>
            </ul>

            <h2 className={`${notoBold.className} mb-4 text-xl`}>Services</h2>
            <p className='mb-4'>Subject to applicable law and unless otherwise communicated, Elevate Now will use commercially reasonable efforts to make the Services available to Registered Users 24 hours a day, 7 days a week, except for</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Planned downtime that will be communicated in advance to Registered Users;</li>
                <li className='mb-4'>Any unavailability caused by circumstances beyond Elevate Now’s reasonable control, including without limitation, acts of God, acts of government, flood, fire, earthquakes, civil unrest, acts of terror, strikes or other labor problems, or internet service provider failures or delays.</li>
                <li className='mb-4'>When such Service is rendered under a time-schedule, in which case, the obligation of Elevate Now under this clause shall be limited to making available such Service during the time-schedule. This obligation will also be subject to (i) and (ii) above;</li>
                <li className='mb-4'>When such Service requires a response/reply from Elevate Now or an HSP, which shall have a standard turnaround time of 48-72 hours. This obligation will also be subject to (i) and (ii) above;</li>
                <li className='mb-4'>When the Registered User is outside the operational coverage of Services</li>
            </ol>
            <ul>
                <li className='mb-4'>Elevate Now has no responsibility towards Unregistered User for providing Services.</li>
                <li className='mb-4'>For the avoidance of doubt, it is hereby clarified that Elevate Now’s responsibility towards Registered User will be limited to the provision of the Services as per the terms and conditions of the Agreement, along with any other terms or conditions that are separately communicated to the Registered User based on the Service availed.</li>
                <li className='mb-4'>If Elevate Now suspects any illegal, wrongful or fraudulent activity on the Application by any User, notwithstanding any other rights Elevate Now may have against such User, Elevate Now reserves the right to inform the relevant government or law enforcement authorities. Elevate Now will cooperate in all investigative procedures or requests for access / information initiated by any such government or law enforcement authorities.</li>
                <li className='mb-4'>Elevate Now reserves the right to add new functionality, remove existing functionality, and modify existing functionality to its Services as and when it deems fit, and make any such changes available in newer versions of Application at its discretion. All Users of its Services will be duly notified upon release of such newer versions and Elevate Now reserves the right to automatically upgrade all Users to the latest version of its Services as and when it deems fit.</li>
                <li className='mb-4'>Elevate Now Services may be subject to certain limitations, such as, limits on storage space, limit on bandwidth, unexpected downtime, unavailability of Elevate Now doctors due to unforeseen circumstances, etc.</li>
                <li className='mb-4'>You may not be eligible to choose a specific HSP for a Service. Elevate Now reserves the right to schedule/reschedule/cancel appointments and select/swap HSPs at any time without prior intimation, based on the information provided by You, Your location and other factors, the accuracy of which is Your responsibility.</li>
                <li className='mb-4'>Elevate Now reserves the right to refuse Service at any time without providing any reasons. In case Elevate Now as received an advance for such Service(s),</li>
                <li className='mb-4'>Elevate Now will either refund the advance or provide credit against such advance for use against any future Service.</li>
            </ul>

            <h2 className={`${notoBold.className} mb-4 text-xl`}>Legal Compliances</h2>
            <ul>
                <li className='mb-4'>Elevate Now will strictly adhere to and adopt all reasonable measures to ensure compliance to all central and state government regulations and directives as applicable from time-to-time.</li>
                <li className='mb-4'>Data Recording, Storage, Encryption & Usage</li>
                <li className='mb-4'>The information stored on the Application may be entered by You or by a HSP in the course of services provided by Elevate Now. The information collected as part of the Services may be stored on Your mobile device, Elevate Now servers within or outside India as well as on a third-party cloud platform (“Cloud Service Provider”) or server located within or outside of India (“Storage Service Provider”).</li>
                <li className='mb-4'>All video-consultations / IM chat consultations / text messages / audios / videos / transcripts / prescriptions / email and hard copy correspondences between Users, who are patients, and HSPs engaged by Elevate Now shall be recorded, saved and stored for record purposes and in the event such records are required to be produced as evidence on the direction of a court of law.</li>
                <li className='mb-4'>It is hereby clarified that Elevate Now does not have the obligation to pre-screen or monitor User Content at any time. However, Elevate Now may elect to monitor any User Content and may modify or remove any User Content from the Application if Elevate Now determines in its sole discretion that such User Content is in violation of this Agreement or any applicable law and best practices. Where Elevate Now removes any User Content from the Application, Elevate Now will make reasonable efforts to inform the Registered User who had posted such User Content.</li>
                <li className='mb-4'>All User Content shall be recorded, saved and stored electronically on a secure cloud database/server managed by the Cloud Service Provider/Data Storage Provider. Elevate Now shall ensure that the Cloud Service Provider/Data Storage Provider uses appropriate levels of encryptions to protect data and takes all necessary precautions. Elevate Now will however not be responsible for any cyber data theft from its Application or the Cloud Service Provider’s/Data Storage Provider’s databases.</li>
                <li className='mb-4'>Elevate Now shall maintain a detailed transaction & purchase history of Users online.</li>
                <li className='mb-4'>After conclusion or termination of any Service, or due to a User’s inactivity for a period of 3 years, Elevate Now reserves the right to permanently delete User Content unless such Service is renewed.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>USER RESPONSIBILITIES</h3>
            <p className='mb-4'>Your use of this Application shall be subjected to the following terms and conditions:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>You will observe and comply with the terms and conditions of the Agreement in letter and spirit;</li>
                <li className='mb-4'>You will provide full and accurate information about Your health, medical history and personal care needs;</li>
                <li className='mb-4'>You will strictly adhere to the advice and instructions given HSPs from time to time;</li>
                <li className='mb-4'>You will not delete or modify any content of the Application including but not limited to, legal notices, disclaimers or proprietary notices such as copyright or trademark symbols, logos, that You do not own or have express permission to modify;</li>
                <li className='mb-4'>You will not decipher, decompile, reverse engineer, or disassemble the Elevate Now content;</li>
                <li className='mb-4'>You will not use any engine, software, tool, agent or other device or mechanism (such as spiders, robots, avatars or intelligent agents) to navigate or search the Application;</li>
                <li className='mb-4'>You will not remove any copyright, trademark registration, or other proprietary notices from the Application. You further agree not to access or use this Application in any manner that may be harmful to the operation of this Application or its content;</li>
                <li className='mb-4'>You will not frame or hotlink or deeplink any Elevate Now Content;</li>
                <li className='mb-4'>You will not use the Application and / or Services in any way that is unlawful, or harms Elevate Now or any other person or entity, as determined in the Elevate Now’s sole discretion.</li>
                <li className='mb-4'>You will not engage in any form of antisocial, disrupting, or destructive acts, including &quot;flaming&quot;, &quot;spamming&quot;, &quot;flooding&quot;, &quot;trolling&quot;, &quot;phishing&quot; and &quot;griefing&quot; as those terms are commonly understood and used on the Internet;</li>
                <li className='mb-4'>You will not host, display, upload, modify, publish, transmit, update or share any information that - </li>
                <ul>
                    <li className='mb-4'>(a) belongs to another person and over which You does not have sufficient legal rights;</li>
                    <li className='mb-4'>(b) is grossly harmful, harassing, blasphemous defamatory, obscene, pornographic, paedophilic, libellous, invasive of another{"'"}s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever;</li>
                    <li className='mb-4'>(c) harm minors in any way;</li>
                    <li className='mb-4'>(d) infringes any patent, trademark, copyright or other proprietary rights (se), violates any law for the time being in force;</li>
                    <li className='mb-4'>(e) deceives or misleads the addressee about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</li>
                    <li className='mb-4'>(f) impersonate another person;</li>
                    <li className='mb-4'>(g) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource;</li>
                    <li className='mb-4'>(h) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</li>
                </ul>
            </ol>

            <p className='mb-4'>Without prejudice to the rights that Elevate Now may have under other provisions of this Agreement, where Elevate Now has reasons to believe that a User has violated a term or condition of this Agreement, then Elevate Now shall, in its sole discretion:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Suspend provision of Services; and/or</li>
                <li className='mb-4'>Suspend the account of the User until there is enough information available with Elevate Now to determine whether the User had violated a term or condition of this Agreement; and/or</li>
                <li className='mb-4'>Suspend or terminate the account of the User where Elevate Now has determined that the User had violated a term or condition of this Agreement; and/or</li>
                <li className='mb-4'>Approach User to make good that loss or damage caused to Elevate Now as a pre-condition to revoke the suspension; and/or</li>
                <li className='mb-4'>Take any such action against the User as it permissible under law; and/or</li>
                <li className='mb-4'>Raise invoice of Services availed by the User; and/or</li>
                <li className='mb-4'>Disable and/or delete such User Content that is in contravention of the Agreement while preserving such information and associated records for the purpose of production to governmental authorities for investigation purposes.</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>PAYMENT, FEES AND TAXES</h3>
            <ul>
                <li className='mb-4'>You agree to pay all subscription fees, consulting fees, reasonable out of pocket expenses and other fees applicable to Your use of the Services. While Elevate Now will strive to give You a fair estimate of fees in advance, the actual fee may be dependent on the type of Services that You purchase and may vary based on the number or duration of the Services subscribed to.</li>
                <li className='mb-4'>It is hereby clarified that unless specifically included in writing, the Services shall not include cost of medicines or additional tests and procedures such as blood tests, MRIs, CT scan, X-Rays etc. Where covered, these costs will be charged at pre-agreed rates to You.</li>
                <li className='mb-4'>You are solely responsible for payment of all taxes, legal compliances, statutory registrations and reporting. Elevate Now is in no way responsible for any of the taxes except for its own income tax.</li>
                <li className='mb-4'>The fees could be paid online through the facility made on the Application. Elevate Now is not associated with any insurance companies, and only self-payments are currently accepted. Third parties support and services are required to process online fee payment. Elevate Now is not responsible for any loss or damage caused to User during this process as these third parties are beyond the control of Elevate Now.</li>
                <li className='mb-4'>All fees are exclusive of taxes. The payment process would be considered to be complete only on receipt of the amount to Elevate Now{"'"}s designated bank account.</li>
                <li className='mb-4'>An invoice for fees against Services received by You will be generated periodically and will be intimated to You on the Application. You may be requested to make the payment immediately or on a deferred basis, at the sole discretion of Elevate Now.  In case the fees against Services are not received within the requested time-frame, Elevate Now reserves the right to stop provision of Services on immediate basis, permanently delete Your account and all information stored against Your account, suspend or terminate the Agreement. You will be solely responsible for the consequences of non-payment for the fees within the requested time-frame and have no right of recovery in any form against Elevate Now.</li>
                <li className='mb-4'>In order to process the payments, Elevate Now might require details of Your bank account, credit card number etc. Please check our privacy policy on how Elevate Now uses the confidential information provided by You.</li>
                <li className='mb-4'>Elevate Now shall send an intimation of receipt of fee from You through an email within 2 working days of receipt of fee.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>ACTIVATION, DELIVERY, REFUNDS & CANCELLATIONS</h3>
            <h2 className={`${notoBold.className} mb-4 tet-xl`}>Activation Policy</h2>
            <ul>
                <li className='mb-4'>For Services that require activation, an executive will get in touch with You within 7 business days of the purchase to help finish all formalities and activate the subscription and deliver necessary activation access within 7 business days of online purchase.</li>
                <li className='mb-4'>For Services that involve scheduling, appointments may be scheduled automatically based on algorigthm (for health coaches) or manually (for doctor consultations) through the Application. We will communicate the availability of the HSP at the time of providing the Service. If You wish to reschedule, You can select a preferred appointment date and time through the Application, subject to the availability of the HSP. While Elevate Now does not guarantee availability of appointment date and time, it will try and confirm appointment as per Your preference. Registered Users are permitted a maximum of two reschedules for Services that require an appointment. Rescheduling is permitted from 1 week up to 1 hour prior to a confirmed appointment.</li>
                <li className='mb-4'>For all Elevate Now Services that require delivery, the estimated delivery date shall be provided to You at the time of placing the order.</li>
                <li className='mb-4'>Certain Elevate Now Services availed by a Registered User may include an onboarding kit, which includes certain hardware equipment required for ease of adherence to the availed Service. This equipment are manufactured by third parties and Elevate Now is not responsible for its quality or functioning, which shall be the sole responsibility of the respective third party. Elevate Now does not accept any liability nor provide and warranty or replacement guarantee for the components of the onboarding kit. You hereby agree and undertake that the equipment provided as part of the onboarding kit shall strictly be for personal use only and shall not be resold or used for any commercial purposes. Elevate Now may require that the equipment be returned in the event of termination of the Service.</li>
            </ul>

            <h2 className={`${notoBold.className} mb-4 text-xl`}>Refund & Cancellation Policy</h2>
            <p className='mb-4'>Unless otherwise communicated to You based on the availed Service, You are free to cancel the Service at any time.</p>
            <p className='mb-4'>Elevate Now shall provide refunds for the Services in the following manner:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Within the first 15 days of availing a Service: No questions asked refund, subject to a deduction of the onboarding fee of INR 5000;</li>
                <li className='mb-4'>Severe adverse effect - full (except onboarding fee) refund at any point of time during the medication period, at the complete discretion of Elevate Now;</li>
                <li className='mb-4'>Refunds shall include cost of the Services only and not the cost of medication or any other additional cost You may have incurred.</li>
                <li className='mb-4'>Medicines once bought will not be eligible for returns/refunds unless wrongly sent or there is a quantity mismatch.</li>
            </ol>
            <p className='mb-4'>Elevate Now may modify the terms of refund at its sole discretion, and any such modification shall be intimated to You.</p>

            <h3 className={`${notoBold.className} mb-4`}>EMERGENCIES</h3>
            <p className='mb-4'>The Services are not a replacement to emergency services offered at hospitals and should not be accessed if the patient is in a critical or unstable state. You should not disregard or delay to seek medical advice based on anything that appears or does not appear on the Application. You should seek emergency help or follow up care when recommended by a Provider or when otherwise needed. Always seek the advice of a physician or other qualified health care provider concerning questions You have regarding a medical condition and before stopping, starting, or modifying any treatment or modification. If You believe you have an emergency, please contact emergency services and/or rush to nearest hospital.</p>

            <h3 className={`${notoBold.className} mb-4`}>REPRESENTATIONS AND WARRANTIES</h3>
            <p className='mb-4'>By Using This Application, You represent and warrant that:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>You are 18 years of age or older and that Your use of the Application shall not violate any applicable law or regulation;</li>
                <li className='mb-4'>All registration information You submit is truthful and accurate and that You agree to maintain the accuracy of such information;</li>
                <li className='mb-4'>You as a Registered User will use the Application solely for Your personal and non-commercial use. Any use of this Application or its content other than for personal purposes is prohibited.</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>Elevate Now represents and warrants that:</h3>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>it is a Limited Liability Partnership organized under the Limited Liability Partnership Act, 2008 and has the power and authority to provide the Services and the Application;</li>
                <li className='mb-4'>it has all permits, approvals and licenses necessary to carry out the Services and in fulfilling its obligations hereunder;</li>
                <li className='mb-4'>by entering into this Agreement, Elevate Now does not violate any of the previous arrangements entered into with other entities to which it is a party;</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>DISCLAIMERS</h3>
            <p className='mb-4'>You understand that there are inherent risks involved in receiving health/medical services over a mobile/computer platform, which include:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Information transmitted may not be sufficient (e.g., poor resolution of images) to allow for appropriate medical decision making by my physician;</li>
                <li className='mb-4'>Your HSP may not be able to provide medical treatment to you nor provide for or arrange for care that You may require in the case of an emergency;</li>
                <li className='mb-4'>Delays in medical evaluation and treatment could occur due to deficiencies or failures of the application/website;</li>
                <li className='mb-4'>Security protocols could fail, causing a breach of privacy of my confidential medical information.</li>
                <li className='mb-4'>A lack of access to complete medical records may result in errors in medical judgment.</li>
            </ol>

            <ul>
                <li className='mb-4'>User may expect the anticipated benefits from the Services provided by Elevate Now or its authorized representatives, but no results can be guaranteed. User’s condition may not be cured or improved, and in some cases, may get worse. Notwithstanding the foregoing, the outcome of any Service availed by You would be subject to your adherence to the advice/plan provided to You.</li>
                <li className='mb-4'>Elevate Now hereby disclaims any responsibility towards Users in terms of development, maintenance and updation of the Application.</li>
                <li className='mb-4'>Any modification, development, maintenance or updation of Application and any modification, transfer, license or assignment of the rights in the Application shall be done by Elevate Now as per its sole judgment and in its sole discretion.</li>
                <li className='mb-4'>The Application and Services provided by Elevate Now is provided &quot;as is,&quot; as available, and without any warranties or conditions (express or implied, including the implied warranties of merchantability, accuracy, fitness for a particular purpose, title and non-infringement, arising by statute or otherwise in law or from a course of dealing or usage or trade). To the fullest extent permitted by law, Elevate Now disclaims all liability arising out of the User{"’"}s use or reliance upon the Application, the Services, the Elevate Now Content, representations and warranties made by Elevate Now or any opinion or suggestion given or expressed by Elevate Now or its contractors and agents (including HSPs).</li>
            </ul>

            <p className='mb-4'>Specifically, Elevate Now disclaims any liability arising out of:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Any pre-existing medical condition; or</li>
                <li className='mb-4'>Any adverse drug reaction (due to any act or omission based on information found on the Application, or otherwise); or</li>
                <li className='mb-4'>Sudden escalation of a prior medical condition or medical situations that occur on account of omission of critical and material health information by a User.</li>
                <li className='mb-4'>Eleavate now will not be responsible for adverse effects of the medications which are otherwise indicated by the pharmaceutical company or can arise from the quality defects in the medicine manufacturing</li>
                <li className='mb-4'>Any delay in medicine delivery if the orders to the same are placed to third party via elevate now infrastructure</li>
            </ol>

            <p className='mb-4'>Elevate Now assumes no responsibility, and shall not be liable for ways in which Your personal data is used. It is the responsibility of You alone to ensure that Your personal data is used in compliance to applicable privacy laws.</p>
            <p className='mb-4'>Elevate Now assumes no responsibility, and shall not be liable for, any damages to, or viruses that may infect User’s equipment on account of User’s access to, use of, or browsing the Application or the downloading of any material, data, text, images, video content, or audio content from the Application. If a User is dissatisfied with the Application, User’s sole remedy is to discontinue using the Application.</p>
            <p className='mb-4'>Neither Elevate Now nor its contractors and agents (including HSPs) shall be liable to a User, monetarily or otherwise, for an occurrence wherein no medical or procedural negligence of Elevate Now or its contractors and agents is proven.</p>

            <h2 className={`${notoBold.className} mb-4 text-xl`}>Information regarding HSP and Services</h2>
            <p className='mb-4'>Information regarding HSP and Elevate Now Services is intended for general reference purposes only. Such information often changes frequently and may become out of date or inaccurate. You are encouraged to independently verify any such information You see on the Application with respect to a HSP that You seek to engage through the Application.</p>
            <p className='mb-4'>ELEVATE NOW DISCLAIMS ANY REPRESENTATION AND/OR WARRANTYFOR THE SECURITY, RELIABILITY, QUALITY, TIMELINESS, AND PERFORMANCE OF</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>THE APPLICATION AND ITS FEATURES;</li>
                <li className='mb-4'>HSP INFORMATION ON THE APPLICATION;</li>
                <li className='mb-4'>ANY INFORMATION, CONTENT OR ADVICE AVAILABLE ON OR RECEIVED THROUGH THE APPLICATION</li>
                <li className='mb-4'>ACCESS TO OR ALTERATION OF USER CONTENT OR ELEVATE NOW CONTENT</li>
                <li className='mb-4'>TRANSMISSIONS OR DATA AND (VI) ANY OTHER MATTER RELATING TO THE APPLICATION AND / OR SERVICES.</li>
            </ol>
            <ul>
                <li className='mb-4'>ELEVATE NOW MAKES NO WARRANTY OR REPRESENTATION THAT ANY ERRORS IN THE APPLICATION WILL BE CORRECTED EXCEPT AS REQUIRED BY LAW.</li>
                <li className='mb-4'>ELEVATE NOW ASSUMES NO RESPONSIBILITY AND/OR LIABILITY WITH RESPECT TO ANY INFORMATION WHICH YOU OR A HSP MAY POST ON THE APPLICATION AND YOU ARE SOLELY RESPONSIBLE FOR SUCH USER CONTENT POSTED ON THE SITE.</li>
                <li className='mb-4'>YOU AGREE THAT THE OPEN AND REAL-TIME NATURE OF THE PLATFORM MAKE IT IMPOSSIBLE FOR ELEVATE NOW TO VOUCH FOR THE VALIDITY, AUTHETICITY AND HONESTY OF USER CONTENT. ELEVATE NOW IS NOT RESPONSIBLE FOR ANY USER CONTENT ON THE APPLICATION, OR FOR THE CONSEQUENCES OF YOU READING OR RELYING ON SUCH CONTENT.</li>
                <li className='mb-4'>ELEVATE NOW DOES NOT PROVIDE ANY GUARANTEE AND SHALL NOT BE HELD LIABLE OR RESPONSIBLE FOR THE FAILURE TO SEND ANY COMMUNICATION, NOTIFICATION OR REMINDER TO YOU WHETHER AS A FEATURE OF THE APPLICATION OR NOT.</li>
                <li className='mb-4'>ELEVATE NOW SHALL NOT BE RESPONSIBLE OR LIABLE FOR ANY BREACH OR LOSS OF DATA INCLUDING PERSONAL INFORMATION CAUSED DUE TO EVENTS BEYOND THE CONTROL OF ELEVATE NOW DUE TO TECHNICAL REASONS OR THIRD PARTY ACTIONS.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>LIMITATION OF LIABILITY</h3>
            <p className='mb-4'>To the fullest extent permitted by law, in no event will Elevate Now or its contractors or agents (including HSPs) or any of their directors, officers, employees, agents or content or service providers (collectively, the “Protected Entities”) be liable for any direct, indirect, special, incidental, punitive, exemplary or consequential damages (including, without limitation, loss of business, revenue, profits, goodwill) arising from, or directly or indirectly related to, the use of, reliance on, or the inability to use or rely on, the Application or the Services, materials and functions related thereto whether or not Elevate Now has been warned of the possibility of such damages or could have reasonably foreseen such damages.</p>
            <p className='mb-4'>Notwithstanding anything to the contrary in this Agreement, in no event shall the total aggregate liability of the Protected Entities to a User for all damages, losses, and causes of action (whether in contract or tort, including, but not limited to, negligence or otherwise) arising from the terms and conditions or a User’s use of the Application exceed, in the aggregate, INR 5000 or the amount of payment against Services that has been directly received by Elevate Now from the User in the past three months. Elevate Now shall not be liable for any damage or loss caused after the expiration of an availed Service.</p>

            <h3 className={`${notoBold.className} mb-4`}>INDEMNIFICATION</h3>
            <p className='mb-4'>You hereby agree to indemnify, defend, and hold Elevate Now, Elevate Now{"'"}s distributors, agents, representatives and other authorized Users (Registered and Non-Registered Users, Patients, HSPs), and each of the foregoing entities{"'"} respective resellers, distributors, service providers and suppliers, and all of the foregoing entities{"'"} respective officers, directors, owners, employees, agents, representatives, harmless from and against any and all losses, damages, liabilities and costs arising from (i) Your use of the Application (ii) Your breach of terms, conditions or provisions of this Agreement and (iii) any negligent or intentional wrongdoing on Your part.</p>

            <h3 className={`${notoBold.className} mb-4`}>USER ACCOUNT SUSPENSION</h3>
            <p className='mb-4'>In the event where a User has breached the Agreement in Elevate Now’s sole judgment or when Elevate Now is unable to verify or authenticate any information provide by User to Elevate Now or when or User fails to provide the consents necessary or desirable for Elevate Now to provide the Services (or after providing such consent, later revokes), Elevate Now reserves the right to suspend and / or terminate Your user account and/or access to the Application by blocking Your IP address or email id with or without notice to You. Any suspected illegal, fraudulent or abusive activity may be grounds for suspending and / or terminating Your account and/or Your access to the Application and/or Services. Upon suspension or termination, Your right to use the features on the Application including Services shall immediately cease and Elevate Now may permanently remove or delete Your information that is available with Elevate Now, including but not limited to login and account information.</p>
            <p className='mb-4'>Elevate Now shall not be liable to User or any third party for any claims or damages arising out of any termination or suspension of User’s account or any other actions taken by Elevate Now in connection with such account termination or suspension.</p>
            <p className='mb-4'>Once User’s account has been temporarily or indefinitely suspended or terminated, User may not continue to use the Application under the same account, a different account or re-register under a new account.</p>

            <h3 className={`${notoBold.className} mb-4`}>TERMINATION</h3>
            <p className='mb-4'>This Agreement will remain in full force and effect while You use the Application in any manner or capacity.</p>
            <p className='mb-4'>You can terminate Your relationship with Elevate Now at any time by providing 90 (ninety) days’ prior written notice to <a className='text-[#3881c5]' href='mailto:info@blog.joinelevatenow.com'>info@blog.joinelevatenow.com</a> We need this period to inactivate User account, only after verifying if there are any ongoing or pending Services. Elevate Now may require User to continue until the completion of an on-going Service should the situation warrant.</p>
            <p className='mb-4'>Elevate Now may terminate its relationship with You after providing 30 (thirty) days’ prior written notice to Your registered email address.  However, it does not prejudice Elevate Now’ right to refuse Service to You without providing any reason.</p>
            <p className='mb-4'>Elevate Now may terminate the Agreement without notice and with immediate effect where, in the sole opinion of Elevate Now:</p>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>Any material particular relating to personal and medical information furnished by a User appears to be untrue; or</li>
                <li className='mb-4'>A User is critical or unstable or dead; or</li>
                <li className='mb-4'>Provision of Services poses a risk to life of HSPs; or</li>
                <li className='mb-4'>Financial dues have not been paid by a User within requested time-frame; or</li>
                <li className='mb-4'>User fails to co-operate with HSPs or displays/does/causes any act that Elevate Now deems to be inappropriate behavior with an HSP; or</li>
                <li className='mb-4'>HSPs and/or other Elevate Now resources are no longer adequate, available and/or suitable to accommodate User’s health requirements.</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>APPLICABLE LAW, JURISDICTION OF COURTS AND DISPUTE RESOLUTION</h3>
            <ul>
                <li className='mb-4'>The information provided under this Application and the terms and conditions therein are governed by and to be interpreted in accordance with Laws of India.</li>
                <li className='mb-4'>All disputes, controversies or claims arising out of or in connection with this Agreement, including any dispute regarding its existence, validity, interpretation, breach or termination, the Parties shall attempt to first amicably resolve such dispute or claim through discussions at the Executive level.</li>
                <li className='mb-4'>If the dispute is not resolved through such discussions within 30 (thirty) days after any of the Parties has served a written notice on the other requesting the commencement of discussions, any Party shall refer the disputes to arbitration which shall be held in accordance with the Arbitration Rules of the Mumbai Centre for International Arbitration (“MCIA Rules”), which rules are deemed to be incorporated by reference in this clause.</li>
                <li className='mb-4'>The seat of arbitration shall be in Mumbai and the language of arbitration proceedings shall be English. The arbitration shall be conducted by 3 (three) arbitrators, one arbitrator to be jointly appointed by Institution and the Principal Investigator; one arbitrator to be appointed by Elevate Now, within 15 (fifteen) business days of receipt of notice above; and the third arbitrator to be jointly appointed by the arbitrators nominated by the respective Parties within 15 (fifteen) business days of the date of appointment of the two nominated arbitrators. In the event the Parties fail to appoint the arbitrators as per the timelines mentioned above, the arbitrators will be appointed in accordance with MCIA Rules.</li>
                <li className='mb-4'>The governing law of the arbitration agreement shall be Indian law.</li>
                <li className='mb-4'>The Parties shall co-operate in good faith to expedite (to the maximum extent practicable) the conduct of any arbitral proceedings commenced under this Agreement.</li>
                <li className='mb-4'>TheParties shall co-operate in good faith to expedite (to the maximum extentpracticable) the conduct of any arbitral proceedings commenced under thisAgreement</li>
                <li className='mb-4'>The Parties agree that any arbitral award shall be final and binding on the Parties.</li>
                <li className='mb-4'>Notwithstanding this clause, each Party may approach the competent courts in Mumbai to obtain urgent interim relief in respect of the subject matter of this Agreement.</li>
                <li className='mb-4'>The Parties agree that the arbitration shall be kept confidential and that the existence of the proceeding and any element of it (including but not limited to any pleadings, briefs or other documents submitted or exchanged, any testimony or other oral submissions, and any awards) shall not be disclosed beyond the tribunal, the Parties, their counsel and any person necessary to the conduct of the proceeding, except insofar as:</li>
            </ul>
            <ol className='mb-4 list-decimal ml-8'>
                <li className='mb-4'>otherwise required by provisions of Applicable Law from which the Parties cannot derogate; or</li>
                <li className='mb-4'>necessary to protect or pursue a legal right or to enforce or challenge an award in bona fide legal proceedings before a state court or other governmental authority.</li>
            </ol>

            <h3 className={`${notoBold.className} mb-4`}>MISCELLANEOUS</h3>
            <ul>
                <li className='mb-4'><span className={`${notoBold.className}`}>Severability :</span> If any provision of this Agreement is held by a court of competent jurisdiction or arbitral tribunal to be unenforceable under applicable law, then such provision shall be excluded from the Agreement and the remainder of the Agreement shall be interpreted as if such provision were so excluded and shall be enforceable in accordance with its terms; provided however that, in such event the Agreement shall be interpreted so as to give effect, to the greatest extent consistent with and permitted by applicable law, to the meaning and intention of the excluded provision as determined by such court of competent jurisdiction or arbitral tribunal.</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>Notices :</span> All notices and other communications required or permitted hereunder to be given to a Party shall be in writing, in the English language, and shall be sent e-mail, or mailed by prepaid internationally-recognized courier or otherwise delivered by hand or by messenger, addressed to such Party{"'"}s address as set forth below or at such other address as the Party shall have furnished to the other Party in writing in accordance with this provision:</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>If to Elevate Now:</span></li>
                <li className='mb-4'><a className='text-[#3881c5]' href='mailto:info@blog.joinelevatenow.com'>info@joinelevatewnow.com</a></li>
                <li className='mb-4'><span className={`${notoBold.className}`}>If to You:</span></li>
                <li className='mb-4'>at the email address provided by You to us when You registered as a User.</li>
                <li className='mb-4'>No term of the Agreement shall be deemed waived and no breach excused, unless such waiver or consent shall be in writing and signed by the Party claimed to have waived or consented. Any consent by any Party to, or waiver of a breach by the other, whether expressed or implied, shall not constitute consent to, waiver of, or excuse for any other different or subsequent breach.</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>Complete Understanding :</span> The Agreement contain the entire understanding of the Parties, and there are no other written or oral understandings or promises between the Parties with respect to the subject matter of the Agreement other than those contained or referenced in the Agreement.</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>Force Majeure :</span> Elevate Now shall not be liable for any downtime or delay or unavailability of the Application caused by circumstances beyond Elevate Now’s reasonable control, including without limitation, acts of God, acts of government, floods, fires, earthquakes, civil unrest, acts of terror, strikes or other labour problems, internet service provider failures or delays, or denial of service attacks.</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>Advertisement : </span>Elevate Now shall have the right to place advertisements and publicity materials of its choice, including that pertaining to parties other than itself for commercial use through electronic means on the Application.</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>Assignment : </span>You may not assign or sub-license, without the prior written consent of Elevate Now, the rights, duties or obligations under this Agreement, in whole or in part, to any person or entity.</li>
                <li className='mb-4'><span className={`${notoBold.className}`}>Conflict : </span> In the event there is any conflict between the terms set out in these Terms of Use, the <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a> and any other policies applicable to specific pages of the Application, the following order of prevalence shall apply:</li>
                <ol className='mb-4 list-decimal ml-8'>
                    <li className='mb-4'>any additional Service-specific terms and conditions that may be agreed by You</li>
                    <li className='mb-4'><a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a></li>
                    <li className='mb-4'>the Terms of Use and</li>
                    <li className='mb-4'>any other policies applicable to specific pages of the Application.</li>
                </ol>
                <li className='mb-4'><span className={`${notoBold.className}`}>Survival : </span>Even after termination, the provisions of the Agreement with respect to Limitation of Liability, Indemnity, Intellectual Property, Dispute Resolution will continue and survive termination.</li>
            </ul>

            <h3 className={`${notoBold.className} mb-4`}>Modifications</h3>
            <p className='mb-4'>Elevate Now reserves the right to modify any part of the Agreement at any time without giving You prior notice. No part of the Agreement shall stand modified unless consented to in writing by Elevate Now.</p>
            <p className='mb-4'>When Elevate Now updates the Agreement, We will send an email to You on Your registered email id which will intimate You of the changes. If You do not agree to the changes, please do not use the Application any further.</p>

            <h3 className={`${notoBold.className} mb-4`}>These Terms of Use were last updated on: 9th September 2022</h3>
            <p className='mb-4'>By choosing to accept this Terms of Use, hereby voluntarily grant Your unequivocal informed consent to Elevate Now’s <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a>, the Elevate Now Mobile Application/Application Terms of Use and receipt of commercial communications from Elevate Now. You further give Your voluntary and informed consent to transfer Your personal data to third parties as specified in the Elevate Now <a className='text-[#3881c5]' href="https://www.joinelevatenow.com/pp/privacy-policy">Privacy Policy</a>.</p>

            {/* <form onSubmit={handleSubmit} action='https://forms.zohopublic.in/agulati/form/TermsOfUseForm/formperma/xzd-IVm_Z2C-PdaDEZRserYvy_8aUlGeQ9O2kZWlivM/htmlRecords/submit' name='form' id='form' method='POST' accept-charset='UTF-8'>
                <div>
                    <input type="hidden" name="zf_referrer_name" value="" />
                    <input type="hidden" name="zf_redirect_url" value="" />
                    <input type="hidden" name="zc_gad" value="" />
                    <input type="checkbox" id="Checkbox_1" name="Checkbox" value="terms agreed" onChange={handleCheckboxChange} />
                    <label className='ml-2' htmlFor="terms-checkbox">I hereby accept the above-mentioned Terms & Condition.</label>
                </div>
                <button disabled={!termsAgreed} className={`${!termsAgreed ? 'opacity-50 cursor-not-allowed' : ''} bg-[#FFCB19] py-4 px-8 rounded-xl mt-4`}>Submit</button>
            </form> */}
        </div>
    )
}

export default TermsOfUse
